---
title: "Policy"
bibliography: references.bib
---

## Manila: using remotely sensed data to deal with urban heat islands

My chosen city is Manila, the capital of the Philippines, located in the northern Philippines archipelago.

![Source: [@angWhereStayManila2019].](Manila.png)

## Summary

Before even starting to discuss Manila specifically, it must be noted that the Philippines ranks as one of the most rapidly urbanising countries in the world, with more than 60% or its population living in cities; what is more, this number is predicted to reach 84% by 2050 [@AddressingUrbanHeat2019]. As a capital city, it is not surprising that Manila is disproportionately burdened by the extreme rates of urban sprawl and population growth the country as a whole is facing.

![Changes in land cover map of Metro Manila indicating urban sprawl growth over a period of 34 years (LANDSAT TM, 23 December 1972, 25 January 1989, and 12 January 2006) [@andongUrbanSprawlPublic2017].](Manila-land-cover.png)

As urban sprawl continues and population growth surges in Metro Manila, the city grapples with a multitude of challenges like traffic congestion, air pollution, informal settlements/slums, inadequate infrastructure, flooding, waste management challenges, longer hotter season (*El Niño Phenomena*), and vulnerability to natural disasters, factors all of which collectively exacerbate the **urban heat island** (i.e.,a phenomenon wherein urban regions encounter higher temperatures compared to adjacent rural areas) problem in the metropolitan area. Urban heat islands (UHI) can lead to heightened risks of health-related issues, heightened energy usage, increased pollution levels, and compromised water quality [@zhouSatelliteRemoteSensing2018]. Given the potential adverse effects on cities and their residents, it's imperative to utilise existing resources and data to identify and measure these impacts.

Through the promotion of inclusivity, safety, and resilience in cities and human settlements, SDG 11, among the United Nations' "17 Sustainable Development Goals", underscores the significant role that cities hold in the global political agenda [@worldbankIssueBriefSDG2017]. SDG Goal 11, aimed at *making cities and human settlements inclusive, safe, resilient, and sustainable*, directly aligns with Manila's context by highlighting the city's ongoing endeavors to combat urban heat island effects, enhance infrastructure resilience, and promote equitable access to green spaces, thereby fostering a more livable and sustainable urban environment for all residents.

In Manila, the responsibility for tackling urban heat island (UHI) issues would likely fall under the jurisdiction of multiple government agencies, including the Department of Environment and Natural Resources (DENR), the Metropolitan Manila Development Authority (MMDA), The Department of Human Settlements and Urban Development (DHSUD), and the local government units (LGUs) of the smaller areal units within Metro Manila (MM). To my knowledge, these agencies often collaborate to implement policies and initiatives aimed at mitigating UHI effects and improving urban climate resilience.

In a relatively recent report to the World Bank, MMDA and DHSUD have outlined their action plan detailing UHI mitigation measures proposed [@AddressingUrbanHeat2019]. Suggested solutions rely heavily on previous successful case studies from cities like Guangzhou (i.e., as a Sponge City — Haizhu wetlands), Paris (i.e., as a Sponge and Waterproof City), and, most importantly, Singapore (i.e, Green Plan 2030, Digital Urban Climate Twin). Science-based UHI strategies through scenario building and comprehensive mapping are identified as a key takeaway, suggested transfer to the MM context includes the following:

-   Capacity-building
    -   Acquisition/development of programs and platforms
    -   Installation and rehabilitation of sensors
    -   Workshops on UHI
-   Identification of Baseline, KPIs and Targets
    -   Stakeholder consultation
        -   Surveys
        -   Multi-agency meetings
-   Geospatial analysis
    -   Mapping of vulnerability of MM cities to UHI
    -   Mapping of existing Urban Green Spaces
-   Monitoring and Evaluation
    -   Assessment through KPIs
    -   Establishment of feedback mechanism
-   Valuation of natural resources

## Applications

While @AddressingUrbanHeat2019 does not go into detailed plans on how this action plan will be implemented in reality, there is no doubt that remotely sensed data will be crucial throughout the process, particularly during the geospatial analysis as well as monitoring and evaluation stages.

For mapping the vulnerability of MM cities to UHI and identifying existing urban green spaces, data from satellites and sensors such as Landsat, Sentinel-2, and MODIS can be utilised. These platforms provide multispectral and thermal imagery suitable for assessing land surface temperature variations and vegetation cover. Additionally, sensors like ASTER (Advanced Spaceborne Thermal Emission and Reflection Radiometer) and WorldView offer high-resolution imagery for detailed analysis of urban features and green spaces. Integrating data from these sources enables comprehensive geospatial analysis to support urban planning and management efforts in addressing UHI and enhancing green infrastructure.

## Limitations

![Source: [@AddressingUrbanHeat2019].](limitations.png)

## Reflections

Learning about the UHI effect must have been my favourite lecture in the module thus far. While it is easy to imagine the dreadful consequences of UHI in either one of the global cities or in the biggest cities of many developing nations usually associated with rapid and uncontrollable urbanisation like Metro Manila, I never gave much thought that Lithuania - specifically Vilnius - might face similar problems. It turns out that the average annual air temperature in central Vilnius typically ranges from 0.59 to 0.88 °C higher than in its suburban areas and the most significant heat island effect, ranging from 0.91 to 1.44 °C, occurs during the warmer months between May and September [@bukantisPeculiaritiesUrbanHeat2022]. While the difference in temperature is not as severe as in MM (\~1°C to 3°C), given the massive difference in numbers of urban population between Vilnius and MM (590,000 vs 13,000,000, respectively) I was quite surprised to learn that it is still an issue. Not to mention, having grown up in Vilnius, I have always seen it as such a spread out city i.e., there are no comparable tightly compact business districts full of skyscrapers and has a plethora of green spaces. I think it would be really interesting to understand how much of a problem the current state of UHI poses in Vilnius and see whether it is being addressed by the officials.
